version: "3.1"

services:
  postgres:
    image: postgres
    container_name: docker-postgres
    ports:
      - "5432:5432"
    networks:
      - postgres-compose
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - data/postgres:/var/lib/postgresql/data
    restart: always

  adminer:
    image: adminer
    container_name: docker-adminer
    ports:
     - "8080:8080"
    networks:
      - postgres-compose
    restart: always
    depends_on:
      - postgres

networks:
  postgres-compose:
    driver: bridge

volumes:
  data/postgres: